//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.237
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace AdminOpciones.SrvTicket84 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="TICKET", ConfigurationName="SrvTicket84.WSTicketSoap")]
    public interface WSTicketSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="TICKET/ConsultaNumeroTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginConsultaNumeroTicket(System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="STREAM")]
        AdminOpciones.SrvTicket84.Return_XML_Ticket EndConsultaNumeroTicket(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class Return_XML_Ticket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Header headerField;
        
        private Ticket dataField;
        
        private LOG_APLICACION lOGField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Header Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Ticket Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LOG_APLICACION LOG {
            get {
                return this.lOGField;
            }
            set {
                this.lOGField = value;
                this.RaisePropertyChanged("LOG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fLAGField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FLAG {
            get {
                return this.fLAGField;
            }
            set {
                this.fLAGField = value;
                this.RaisePropertyChanged("FLAG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class LOG_RETURN_VALUE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string spField;
        
        private string rETORNOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SP {
            get {
                return this.spField;
            }
            set {
                this.spField = value;
                this.RaisePropertyChanged("SP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RETORNO {
            get {
                return this.rETORNOField;
            }
            set {
                this.rETORNOField = value;
                this.RaisePropertyChanged("RETORNO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class LOG_SQL_EXCEPTION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string eRRORField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class LOG_EVENTOS_DATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string eRRORField;
        
        private string mENSAJEField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
                this.RaisePropertyChanged("MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class LOG_CONEXION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string sERVIDORField;
        
        private string bASEField;
        
        private string eSTADOField;
        
        private string hORAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SERVIDOR {
            get {
                return this.sERVIDORField;
            }
            set {
                this.sERVIDORField = value;
                this.RaisePropertyChanged("SERVIDOR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BASE {
            get {
                return this.bASEField;
            }
            set {
                this.bASEField = value;
                this.RaisePropertyChanged("BASE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HORA {
            get {
                return this.hORAField;
            }
            set {
                this.hORAField = value;
                this.RaisePropertyChanged("HORA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class LOG_ERRORES_APLICACION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hORAField;
        
        private string lINEAField;
        
        private string mETODOField;
        
        private string cLASEField;
        
        private string eRRORField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HORA {
            get {
                return this.hORAField;
            }
            set {
                this.hORAField = value;
                this.RaisePropertyChanged("HORA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LINEA {
            get {
                return this.lINEAField;
            }
            set {
                this.lINEAField = value;
                this.RaisePropertyChanged("LINEA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string METODO {
            get {
                return this.mETODOField;
            }
            set {
                this.mETODOField = value;
                this.RaisePropertyChanged("METODO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CLASE {
            get {
                return this.cLASEField;
            }
            set {
                this.cLASEField = value;
                this.RaisePropertyChanged("CLASE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class LOG_APLICACION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LOG_ERRORES_APLICACION[] eVENTO_APLICACIONField;
        
        private LOG_CONEXION[] eVENTO_CONEXIONField;
        
        private LOG_EVENTOS_DATA[] eVENTO_DATAField;
        
        private LOG_SQL_EXCEPTION[] eVENTO_SQL_EXCEPTIONField;
        
        private LOG_RETURN_VALUE[] rETURN_VALUEField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LOG_ERRORES_APLICACION[] EVENTO_APLICACION {
            get {
                return this.eVENTO_APLICACIONField;
            }
            set {
                this.eVENTO_APLICACIONField = value;
                this.RaisePropertyChanged("EVENTO_APLICACION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LOG_CONEXION[] EVENTO_CONEXION {
            get {
                return this.eVENTO_CONEXIONField;
            }
            set {
                this.eVENTO_CONEXIONField = value;
                this.RaisePropertyChanged("EVENTO_CONEXION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LOG_EVENTOS_DATA[] EVENTO_DATA {
            get {
                return this.eVENTO_DATAField;
            }
            set {
                this.eVENTO_DATAField = value;
                this.RaisePropertyChanged("EVENTO_DATA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public LOG_SQL_EXCEPTION[] EVENTO_SQL_EXCEPTION {
            get {
                return this.eVENTO_SQL_EXCEPTIONField;
            }
            set {
                this.eVENTO_SQL_EXCEPTIONField = value;
                this.RaisePropertyChanged("EVENTO_SQL_EXCEPTION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public LOG_RETURN_VALUE[] RETURN_VALUE {
            get {
                return this.rETURN_VALUEField;
            }
            set {
                this.rETURN_VALUEField = value;
                this.RaisePropertyChanged("RETURN_VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TICKET")]
    public partial class Ticket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tICKETField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TICKET {
            get {
                return this.tICKETField;
            }
            set {
                this.tICKETField = value;
                this.RaisePropertyChanged("TICKET");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSTicketSoapChannel : AdminOpciones.SrvTicket84.WSTicketSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaNumeroTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaNumeroTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AdminOpciones.SrvTicket84.Return_XML_Ticket Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AdminOpciones.SrvTicket84.Return_XML_Ticket)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTicketSoapClient : System.ServiceModel.ClientBase<AdminOpciones.SrvTicket84.WSTicketSoap>, AdminOpciones.SrvTicket84.WSTicketSoap {
        
        private BeginOperationDelegate onBeginConsultaNumeroTicketDelegate;
        
        private EndOperationDelegate onEndConsultaNumeroTicketDelegate;
        
        private System.Threading.SendOrPostCallback onConsultaNumeroTicketCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WSTicketSoapClient() {
        }
        
        public WSTicketSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTicketSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTicketSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTicketSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ConsultaNumeroTicketCompletedEventArgs> ConsultaNumeroTicketCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvTicket84.WSTicketSoap.BeginConsultaNumeroTicket(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaNumeroTicket(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminOpciones.SrvTicket84.Return_XML_Ticket AdminOpciones.SrvTicket84.WSTicketSoap.EndConsultaNumeroTicket(System.IAsyncResult result) {
            return base.Channel.EndConsultaNumeroTicket(result);
        }
        
        private System.IAsyncResult OnBeginConsultaNumeroTicket(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AdminOpciones.SrvTicket84.WSTicketSoap)(this)).BeginConsultaNumeroTicket(callback, asyncState);
        }
        
        private object[] OnEndConsultaNumeroTicket(System.IAsyncResult result) {
            AdminOpciones.SrvTicket84.Return_XML_Ticket retVal = ((AdminOpciones.SrvTicket84.WSTicketSoap)(this)).EndConsultaNumeroTicket(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaNumeroTicketCompleted(object state) {
            if ((this.ConsultaNumeroTicketCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaNumeroTicketCompleted(this, new ConsultaNumeroTicketCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaNumeroTicketAsync() {
            this.ConsultaNumeroTicketAsync(null);
        }
        
        public void ConsultaNumeroTicketAsync(object userState) {
            if ((this.onBeginConsultaNumeroTicketDelegate == null)) {
                this.onBeginConsultaNumeroTicketDelegate = new BeginOperationDelegate(this.OnBeginConsultaNumeroTicket);
            }
            if ((this.onEndConsultaNumeroTicketDelegate == null)) {
                this.onEndConsultaNumeroTicketDelegate = new EndOperationDelegate(this.OnEndConsultaNumeroTicket);
            }
            if ((this.onConsultaNumeroTicketCompletedDelegate == null)) {
                this.onConsultaNumeroTicketCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaNumeroTicketCompleted);
            }
            base.InvokeAsync(this.onBeginConsultaNumeroTicketDelegate, null, this.onEndConsultaNumeroTicketDelegate, this.onConsultaNumeroTicketCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AdminOpciones.SrvTicket84.WSTicketSoap CreateChannel() {
            return new WSTicketSoapClientChannel(this);
        }
        
        private class WSTicketSoapClientChannel : ChannelBase<AdminOpciones.SrvTicket84.WSTicketSoap>, AdminOpciones.SrvTicket84.WSTicketSoap {
            
            public WSTicketSoapClientChannel(System.ServiceModel.ClientBase<AdminOpciones.SrvTicket84.WSTicketSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginConsultaNumeroTicket(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ConsultaNumeroTicket", _args, callback, asyncState);
                return _result;
            }
            
            public AdminOpciones.SrvTicket84.Return_XML_Ticket EndConsultaNumeroTicket(System.IAsyncResult result) {
                object[] _args = new object[0];
                AdminOpciones.SrvTicket84.Return_XML_Ticket _result = ((AdminOpciones.SrvTicket84.Return_XML_Ticket)(base.EndInvoke("ConsultaNumeroTicket", _args, result)));
                return _result;
            }
        }
    }
}
