//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace AdminOpciones.SrvTomaLinea {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyClientResult", Namespace="http://schemas.datacontract.org/2004/07/ProxyServiceSAO")]
    public partial class ProxyClientResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdStatusCodeField;
        
        private string MsgStatusCodeField;
        
        private string ReturnCodeField;
        
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdStatusCode {
            get {
                return this.AdStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdStatusCodeField, value) != true)) {
                    this.AdStatusCodeField = value;
                    this.RaisePropertyChanged("AdStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgStatusCode {
            get {
                return this.MsgStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgStatusCodeField, value) != true)) {
                    this.MsgStatusCodeField = value;
                    this.RaisePropertyChanged("MsgStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnCodeField, value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvTomaLinea.IProxyLineaCredito")]
    public interface IProxyLineaCredito {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProxyLineaCredito/getLineaCode", ReplyAction="http://tempuri.org/IProxyLineaCredito/getLineaCodeResponse")]
        System.IAsyncResult BegingetLineaCode(string clienteAS400, string codigoCliente, string facility, string plazoOP, string montoLinea, string monedaAS400, string action, System.AsyncCallback callback, object asyncState);
        
        AdminOpciones.SrvTomaLinea.ProxyClientResult EndgetLineaCode(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyLineaCreditoChannel : AdminOpciones.SrvTomaLinea.IProxyLineaCredito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getLineaCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getLineaCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AdminOpciones.SrvTomaLinea.ProxyClientResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AdminOpciones.SrvTomaLinea.ProxyClientResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyLineaCreditoClient : System.ServiceModel.ClientBase<AdminOpciones.SrvTomaLinea.IProxyLineaCredito>, AdminOpciones.SrvTomaLinea.IProxyLineaCredito {
        
        private BeginOperationDelegate onBegingetLineaCodeDelegate;
        
        private EndOperationDelegate onEndgetLineaCodeDelegate;
        
        private System.Threading.SendOrPostCallback ongetLineaCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProxyLineaCreditoClient() {
        }
        
        public ProxyLineaCreditoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyLineaCreditoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyLineaCreditoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyLineaCreditoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getLineaCodeCompletedEventArgs> getLineaCodeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvTomaLinea.IProxyLineaCredito.BegingetLineaCode(string clienteAS400, string codigoCliente, string facility, string plazoOP, string montoLinea, string monedaAS400, string action, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetLineaCode(clienteAS400, codigoCliente, facility, plazoOP, montoLinea, monedaAS400, action, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminOpciones.SrvTomaLinea.ProxyClientResult AdminOpciones.SrvTomaLinea.IProxyLineaCredito.EndgetLineaCode(System.IAsyncResult result) {
            return base.Channel.EndgetLineaCode(result);
        }
        
        private System.IAsyncResult OnBegingetLineaCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string clienteAS400 = ((string)(inValues[0]));
            string codigoCliente = ((string)(inValues[1]));
            string facility = ((string)(inValues[2]));
            string plazoOP = ((string)(inValues[3]));
            string montoLinea = ((string)(inValues[4]));
            string monedaAS400 = ((string)(inValues[5]));
            string action = ((string)(inValues[6]));
            return ((AdminOpciones.SrvTomaLinea.IProxyLineaCredito)(this)).BegingetLineaCode(clienteAS400, codigoCliente, facility, plazoOP, montoLinea, monedaAS400, action, callback, asyncState);
        }
        
        private object[] OnEndgetLineaCode(System.IAsyncResult result) {
            AdminOpciones.SrvTomaLinea.ProxyClientResult retVal = ((AdminOpciones.SrvTomaLinea.IProxyLineaCredito)(this)).EndgetLineaCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetLineaCodeCompleted(object state) {
            if ((this.getLineaCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getLineaCodeCompleted(this, new getLineaCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getLineaCodeAsync(string clienteAS400, string codigoCliente, string facility, string plazoOP, string montoLinea, string monedaAS400, string action) {
            this.getLineaCodeAsync(clienteAS400, codigoCliente, facility, plazoOP, montoLinea, monedaAS400, action, null);
        }
        
        public void getLineaCodeAsync(string clienteAS400, string codigoCliente, string facility, string plazoOP, string montoLinea, string monedaAS400, string action, object userState) {
            if ((this.onBegingetLineaCodeDelegate == null)) {
                this.onBegingetLineaCodeDelegate = new BeginOperationDelegate(this.OnBegingetLineaCode);
            }
            if ((this.onEndgetLineaCodeDelegate == null)) {
                this.onEndgetLineaCodeDelegate = new EndOperationDelegate(this.OnEndgetLineaCode);
            }
            if ((this.ongetLineaCodeCompletedDelegate == null)) {
                this.ongetLineaCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetLineaCodeCompleted);
            }
            base.InvokeAsync(this.onBegingetLineaCodeDelegate, new object[] {
                        clienteAS400,
                        codigoCliente,
                        facility,
                        plazoOP,
                        montoLinea,
                        monedaAS400,
                        action}, this.onEndgetLineaCodeDelegate, this.ongetLineaCodeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AdminOpciones.SrvTomaLinea.IProxyLineaCredito CreateChannel() {
            return new ProxyLineaCreditoClientChannel(this);
        }
        
        private class ProxyLineaCreditoClientChannel : ChannelBase<AdminOpciones.SrvTomaLinea.IProxyLineaCredito>, AdminOpciones.SrvTomaLinea.IProxyLineaCredito {
            
            public ProxyLineaCreditoClientChannel(System.ServiceModel.ClientBase<AdminOpciones.SrvTomaLinea.IProxyLineaCredito> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetLineaCode(string clienteAS400, string codigoCliente, string facility, string plazoOP, string montoLinea, string monedaAS400, string action, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[7];
                _args[0] = clienteAS400;
                _args[1] = codigoCliente;
                _args[2] = facility;
                _args[3] = plazoOP;
                _args[4] = montoLinea;
                _args[5] = monedaAS400;
                _args[6] = action;
                System.IAsyncResult _result = base.BeginInvoke("getLineaCode", _args, callback, asyncState);
                return _result;
            }
            
            public AdminOpciones.SrvTomaLinea.ProxyClientResult EndgetLineaCode(System.IAsyncResult result) {
                object[] _args = new object[0];
                AdminOpciones.SrvTomaLinea.ProxyClientResult _result = ((AdminOpciones.SrvTomaLinea.ProxyClientResult)(base.EndInvoke("getLineaCode", _args, result)));
                return _result;
            }
        }
    }
}
