//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsTest.ServiceWSReport {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessType", Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public enum ProcessType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Input = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Output = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://fmdsfmc.corpbanca.cl/fmd", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd", ConfigurationName="ServiceWSReport.wsReportServicesSoap")]
    public interface wsReportServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reportType del espacio de nombres http://fmdsfmc.corpbanca.cl/fmd no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://fmdsfmc.corpbanca.cl/fmd/GenerateAndSendReports", ReplyAction="*")]
        wsTest.ServiceWSReport.GenerateAndSendReportsResponse GenerateAndSendReports(wsTest.ServiceWSReport.GenerateAndSendReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://fmdsfmc.corpbanca.cl/fmd/GenerateAndSendReports", ReplyAction="*")]
        System.IAsyncResult BeginGenerateAndSendReports(wsTest.ServiceWSReport.GenerateAndSendReportsRequest request, System.AsyncCallback callback, object asyncState);
        
        wsTest.ServiceWSReport.GenerateAndSendReportsResponse EndGenerateAndSendReports(System.IAsyncResult result);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reportType del espacio de nombres http://fmdsfmc.corpbanca.cl/fmd no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://fmdsfmc.corpbanca.cl/fmd/Automated_RCM_SendReports", ReplyAction="*")]
        wsTest.ServiceWSReport.Automated_RCM_SendReportsResponse Automated_RCM_SendReports(wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://fmdsfmc.corpbanca.cl/fmd/Automated_RCM_SendReports", ReplyAction="*")]
        System.IAsyncResult BeginAutomated_RCM_SendReports(wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest request, System.AsyncCallback callback, object asyncState);
        
        wsTest.ServiceWSReport.Automated_RCM_SendReportsResponse EndAutomated_RCM_SendReports(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAndSendReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAndSendReports", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public wsTest.ServiceWSReport.GenerateAndSendReportsRequestBody Body;
        
        public GenerateAndSendReportsRequest() {
        }
        
        public GenerateAndSendReportsRequest(wsTest.ServiceWSReport.GenerateAndSendReportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class GenerateAndSendReportsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public wsTest.ServiceWSReport.ProcessType process;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reportType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool withMergeFiles;
        
        public GenerateAndSendReportsRequestBody() {
        }
        
        public GenerateAndSendReportsRequestBody(wsTest.ServiceWSReport.ProcessType process, string reportType, string modulo, string date, bool withMergeFiles) {
            this.process = process;
            this.reportType = reportType;
            this.modulo = modulo;
            this.date = date;
            this.withMergeFiles = withMergeFiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAndSendReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAndSendReportsResponse", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public wsTest.ServiceWSReport.GenerateAndSendReportsResponseBody Body;
        
        public GenerateAndSendReportsResponse() {
        }
        
        public GenerateAndSendReportsResponse(wsTest.ServiceWSReport.GenerateAndSendReportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class GenerateAndSendReportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GenerateAndSendReportsResult;
        
        public GenerateAndSendReportsResponseBody() {
        }
        
        public GenerateAndSendReportsResponseBody(object GenerateAndSendReportsResult) {
            this.GenerateAndSendReportsResult = GenerateAndSendReportsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Automated_RCM_SendReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Automated_RCM_SendReports", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public wsTest.ServiceWSReport.Automated_RCM_SendReportsRequestBody Body;
        
        public Automated_RCM_SendReportsRequest() {
        }
        
        public Automated_RCM_SendReportsRequest(wsTest.ServiceWSReport.Automated_RCM_SendReportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class Automated_RCM_SendReportsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public wsTest.ServiceWSReport.ProcessType process;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reportType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        public Automated_RCM_SendReportsRequestBody() {
        }
        
        public Automated_RCM_SendReportsRequestBody(wsTest.ServiceWSReport.ProcessType process, string reportType, string date) {
            this.process = process;
            this.reportType = reportType;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Automated_RCM_SendReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Automated_RCM_SendReportsResponse", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public wsTest.ServiceWSReport.Automated_RCM_SendReportsResponseBody Body;
        
        public Automated_RCM_SendReportsResponse() {
        }
        
        public Automated_RCM_SendReportsResponse(wsTest.ServiceWSReport.Automated_RCM_SendReportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class Automated_RCM_SendReportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsTest.ServiceWSReport.ArrayOfString Automated_RCM_SendReportsResult;
        
        public Automated_RCM_SendReportsResponseBody() {
        }
        
        public Automated_RCM_SendReportsResponseBody(wsTest.ServiceWSReport.ArrayOfString Automated_RCM_SendReportsResult) {
            this.Automated_RCM_SendReportsResult = Automated_RCM_SendReportsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsReportServicesSoapChannel : wsTest.ServiceWSReport.wsReportServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerateAndSendReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GenerateAndSendReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Automated_RCM_SendReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Automated_RCM_SendReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public wsTest.ServiceWSReport.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((wsTest.ServiceWSReport.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsReportServicesSoapClient : System.ServiceModel.ClientBase<wsTest.ServiceWSReport.wsReportServicesSoap>, wsTest.ServiceWSReport.wsReportServicesSoap {
        
        private BeginOperationDelegate onBeginGenerateAndSendReportsDelegate;
        
        private EndOperationDelegate onEndGenerateAndSendReportsDelegate;
        
        private System.Threading.SendOrPostCallback onGenerateAndSendReportsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAutomated_RCM_SendReportsDelegate;
        
        private EndOperationDelegate onEndAutomated_RCM_SendReportsDelegate;
        
        private System.Threading.SendOrPostCallback onAutomated_RCM_SendReportsCompletedDelegate;
        
        public wsReportServicesSoapClient() {
        }
        
        public wsReportServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsReportServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReportServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReportServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GenerateAndSendReportsCompletedEventArgs> GenerateAndSendReportsCompleted;
        
        public event System.EventHandler<Automated_RCM_SendReportsCompletedEventArgs> Automated_RCM_SendReportsCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTest.ServiceWSReport.GenerateAndSendReportsResponse wsTest.ServiceWSReport.wsReportServicesSoap.GenerateAndSendReports(wsTest.ServiceWSReport.GenerateAndSendReportsRequest request) {
            return base.Channel.GenerateAndSendReports(request);
        }
        
        public object GenerateAndSendReports(wsTest.ServiceWSReport.ProcessType process, string reportType, string modulo, string date, bool withMergeFiles) {
            wsTest.ServiceWSReport.GenerateAndSendReportsRequest inValue = new wsTest.ServiceWSReport.GenerateAndSendReportsRequest();
            inValue.Body = new wsTest.ServiceWSReport.GenerateAndSendReportsRequestBody();
            inValue.Body.process = process;
            inValue.Body.reportType = reportType;
            inValue.Body.modulo = modulo;
            inValue.Body.date = date;
            inValue.Body.withMergeFiles = withMergeFiles;
            wsTest.ServiceWSReport.GenerateAndSendReportsResponse retVal = ((wsTest.ServiceWSReport.wsReportServicesSoap)(this)).GenerateAndSendReports(inValue);
            return retVal.Body.GenerateAndSendReportsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult wsTest.ServiceWSReport.wsReportServicesSoap.BeginGenerateAndSendReports(wsTest.ServiceWSReport.GenerateAndSendReportsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGenerateAndSendReports(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGenerateAndSendReports(wsTest.ServiceWSReport.ProcessType process, string reportType, string modulo, string date, bool withMergeFiles, System.AsyncCallback callback, object asyncState) {
            wsTest.ServiceWSReport.GenerateAndSendReportsRequest inValue = new wsTest.ServiceWSReport.GenerateAndSendReportsRequest();
            inValue.Body = new wsTest.ServiceWSReport.GenerateAndSendReportsRequestBody();
            inValue.Body.process = process;
            inValue.Body.reportType = reportType;
            inValue.Body.modulo = modulo;
            inValue.Body.date = date;
            inValue.Body.withMergeFiles = withMergeFiles;
            return ((wsTest.ServiceWSReport.wsReportServicesSoap)(this)).BeginGenerateAndSendReports(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTest.ServiceWSReport.GenerateAndSendReportsResponse wsTest.ServiceWSReport.wsReportServicesSoap.EndGenerateAndSendReports(System.IAsyncResult result) {
            return base.Channel.EndGenerateAndSendReports(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public object EndGenerateAndSendReports(System.IAsyncResult result) {
            wsTest.ServiceWSReport.GenerateAndSendReportsResponse retVal = ((wsTest.ServiceWSReport.wsReportServicesSoap)(this)).EndGenerateAndSendReports(result);
            return retVal.Body.GenerateAndSendReportsResult;
        }
        
        private System.IAsyncResult OnBeginGenerateAndSendReports(object[] inValues, System.AsyncCallback callback, object asyncState) {
            wsTest.ServiceWSReport.ProcessType process = ((wsTest.ServiceWSReport.ProcessType)(inValues[0]));
            string reportType = ((string)(inValues[1]));
            string modulo = ((string)(inValues[2]));
            string date = ((string)(inValues[3]));
            bool withMergeFiles = ((bool)(inValues[4]));
            return this.BeginGenerateAndSendReports(process, reportType, modulo, date, withMergeFiles, callback, asyncState);
        }
        
        private object[] OnEndGenerateAndSendReports(System.IAsyncResult result) {
            object retVal = this.EndGenerateAndSendReports(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGenerateAndSendReportsCompleted(object state) {
            if ((this.GenerateAndSendReportsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GenerateAndSendReportsCompleted(this, new GenerateAndSendReportsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GenerateAndSendReportsAsync(wsTest.ServiceWSReport.ProcessType process, string reportType, string modulo, string date, bool withMergeFiles) {
            this.GenerateAndSendReportsAsync(process, reportType, modulo, date, withMergeFiles, null);
        }
        
        public void GenerateAndSendReportsAsync(wsTest.ServiceWSReport.ProcessType process, string reportType, string modulo, string date, bool withMergeFiles, object userState) {
            if ((this.onBeginGenerateAndSendReportsDelegate == null)) {
                this.onBeginGenerateAndSendReportsDelegate = new BeginOperationDelegate(this.OnBeginGenerateAndSendReports);
            }
            if ((this.onEndGenerateAndSendReportsDelegate == null)) {
                this.onEndGenerateAndSendReportsDelegate = new EndOperationDelegate(this.OnEndGenerateAndSendReports);
            }
            if ((this.onGenerateAndSendReportsCompletedDelegate == null)) {
                this.onGenerateAndSendReportsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGenerateAndSendReportsCompleted);
            }
            base.InvokeAsync(this.onBeginGenerateAndSendReportsDelegate, new object[] {
                        process,
                        reportType,
                        modulo,
                        date,
                        withMergeFiles}, this.onEndGenerateAndSendReportsDelegate, this.onGenerateAndSendReportsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTest.ServiceWSReport.Automated_RCM_SendReportsResponse wsTest.ServiceWSReport.wsReportServicesSoap.Automated_RCM_SendReports(wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest request) {
            return base.Channel.Automated_RCM_SendReports(request);
        }
        
        public wsTest.ServiceWSReport.ArrayOfString Automated_RCM_SendReports(wsTest.ServiceWSReport.ProcessType process, string reportType, string date) {
            wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest inValue = new wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest();
            inValue.Body = new wsTest.ServiceWSReport.Automated_RCM_SendReportsRequestBody();
            inValue.Body.process = process;
            inValue.Body.reportType = reportType;
            inValue.Body.date = date;
            wsTest.ServiceWSReport.Automated_RCM_SendReportsResponse retVal = ((wsTest.ServiceWSReport.wsReportServicesSoap)(this)).Automated_RCM_SendReports(inValue);
            return retVal.Body.Automated_RCM_SendReportsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult wsTest.ServiceWSReport.wsReportServicesSoap.BeginAutomated_RCM_SendReports(wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAutomated_RCM_SendReports(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAutomated_RCM_SendReports(wsTest.ServiceWSReport.ProcessType process, string reportType, string date, System.AsyncCallback callback, object asyncState) {
            wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest inValue = new wsTest.ServiceWSReport.Automated_RCM_SendReportsRequest();
            inValue.Body = new wsTest.ServiceWSReport.Automated_RCM_SendReportsRequestBody();
            inValue.Body.process = process;
            inValue.Body.reportType = reportType;
            inValue.Body.date = date;
            return ((wsTest.ServiceWSReport.wsReportServicesSoap)(this)).BeginAutomated_RCM_SendReports(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTest.ServiceWSReport.Automated_RCM_SendReportsResponse wsTest.ServiceWSReport.wsReportServicesSoap.EndAutomated_RCM_SendReports(System.IAsyncResult result) {
            return base.Channel.EndAutomated_RCM_SendReports(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public wsTest.ServiceWSReport.ArrayOfString EndAutomated_RCM_SendReports(System.IAsyncResult result) {
            wsTest.ServiceWSReport.Automated_RCM_SendReportsResponse retVal = ((wsTest.ServiceWSReport.wsReportServicesSoap)(this)).EndAutomated_RCM_SendReports(result);
            return retVal.Body.Automated_RCM_SendReportsResult;
        }
        
        private System.IAsyncResult OnBeginAutomated_RCM_SendReports(object[] inValues, System.AsyncCallback callback, object asyncState) {
            wsTest.ServiceWSReport.ProcessType process = ((wsTest.ServiceWSReport.ProcessType)(inValues[0]));
            string reportType = ((string)(inValues[1]));
            string date = ((string)(inValues[2]));
            return this.BeginAutomated_RCM_SendReports(process, reportType, date, callback, asyncState);
        }
        
        private object[] OnEndAutomated_RCM_SendReports(System.IAsyncResult result) {
            wsTest.ServiceWSReport.ArrayOfString retVal = this.EndAutomated_RCM_SendReports(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAutomated_RCM_SendReportsCompleted(object state) {
            if ((this.Automated_RCM_SendReportsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Automated_RCM_SendReportsCompleted(this, new Automated_RCM_SendReportsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Automated_RCM_SendReportsAsync(wsTest.ServiceWSReport.ProcessType process, string reportType, string date) {
            this.Automated_RCM_SendReportsAsync(process, reportType, date, null);
        }
        
        public void Automated_RCM_SendReportsAsync(wsTest.ServiceWSReport.ProcessType process, string reportType, string date, object userState) {
            if ((this.onBeginAutomated_RCM_SendReportsDelegate == null)) {
                this.onBeginAutomated_RCM_SendReportsDelegate = new BeginOperationDelegate(this.OnBeginAutomated_RCM_SendReports);
            }
            if ((this.onEndAutomated_RCM_SendReportsDelegate == null)) {
                this.onEndAutomated_RCM_SendReportsDelegate = new EndOperationDelegate(this.OnEndAutomated_RCM_SendReports);
            }
            if ((this.onAutomated_RCM_SendReportsCompletedDelegate == null)) {
                this.onAutomated_RCM_SendReportsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAutomated_RCM_SendReportsCompleted);
            }
            base.InvokeAsync(this.onBeginAutomated_RCM_SendReportsDelegate, new object[] {
                        process,
                        reportType,
                        date}, this.onEndAutomated_RCM_SendReportsDelegate, this.onAutomated_RCM_SendReportsCompletedDelegate, userState);
        }
    }
}
