USE BacParamSuda
GO

DECLARE @Existe INT
SET @Existe = 0
SELECT @Existe = 1 FROM TABLA_GENERAL_GLOBAL  WHERE ctcateg = 8608

IF @Existe = 0
BEGIN
	
	INSERT INTO TABLA_GENERAL_GLOBAL  VALUES(8608,'EMAIL INICIO DIA',1,1,0,0,1,0,0,0,'') 
	
END



DECLARE @ExisteDetalle INT
SET @ExisteDetalle = 0
SELECT @ExisteDetalle = 1 FROM TABLA_GENERAL_DETALLE  WHERE tbcateg = 8608

IF @ExisteDetalle = 0

BEGIN
	
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,1,0,GETDATE(),0,'Apertura Sistemas Bac','ASUNTO')   
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,2,0,GETDATE(),0,'Estimados,
	Sistemas Bac Abiertos','CUERPO')  

	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,3,0,GETDATE(),0,'Luis.Guerra.D@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,4,0,GETDATE(),0,'ximena.torrico@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,5,0,GETDATE(),0,'julio.penaloza@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,6,0,GETDATE(),0,'Paulina.Concha@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,7,0,GETDATE(),0,'borislav.delic@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,8,0,GETDATE(),0,'pablo.umana@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,9,0,GETDATE(),0,'pablo.martinez@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,10,0,GETDATE(),0,'Matias.Arangua@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,11,0,GETDATE(),0,'Nelson.Acuna@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,12,0,GETDATE(),0,'mariafrancisca.cifuentes@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,13,0,GETDATE(),0,'soledad.brinck@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,14,0,GETDATE(),0,'roberto.fuentes@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,15,0,GETDATE(),0,'roberto.navarrete@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,16,0,GETDATE(),0,'juanpablo.tuteleers@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,17,0,GETDATE(),0,'elizabeth.silva@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,18,0,GETDATE(),0,'Hugo.Rios@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,19,0,GETDATE(),0,'nolberto.linares@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,20,0,GETDATE(),0,'jorge.jaramillo@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,21,0,GETDATE(),0,'david.tonda@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,22,0,GETDATE(),0,'pablo.huidobro@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,23,0,GETDATE(),0,'paola.rossi@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,24,0,GETDATE(),0,'paula.villena@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,25,0,GETDATE(),0,'jose.vives@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,26,0,GETDATE(),0,'jocelyn.flores@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,27,0,GETDATE(),0,'Patricio.Orellana@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,28,0,GETDATE(),0,'Cristian.Forno@Corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,29,0,GETDATE(),0,'esteban.alvarado@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,30,0,GETDATE(),0,'Andres.Caprile@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,31,0,GETDATE(),0,'andres.grau@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,32,0,GETDATE(),0,'Maria.Diaz.F@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,33,0,GETDATE(),0,'Javier.Delrio@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,34,0,GETDATE(),0,'tomas.salgado@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,35,0,GETDATE(),0,'darwin.yanez@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,36,0,GETDATE(),0,'daniel.santamaria@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,37,0,GETDATE(),0,'michel.goffard@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,38,0,GETDATE(),0,'Cristian.Mascareno@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,39,0,GETDATE(),0,'adrian.gonzalez@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,40,0,GETDATE(),0,'carlos.basterrica@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,41,0,GETDATE(),0,'Paolo.Moya@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,42,0,GETDATE(),0,'kenneth.rothery@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,43,0,GETDATE(),0,'marcelo.vidal@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,44,0,GETDATE(),0,'Maria.Navarro@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,45,0,GETDATE(),0,'claudia.bravo@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,46,0,GETDATE(),0,'maritza.campos@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,47,0,GETDATE(),0,'cristobal.jara@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,48,0,GETDATE(),0,'MariaElena.Vergara@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,49,0,GETDATE(),0,'Francisco.Ochoa@Corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,50,0,GETDATE(),0,'franco.osorio@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,51,0,GETDATE(),0,'jennifer.diaz@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,52,0,GETDATE(),0,'fabiola.torrejon@corpbanca.cl','DESTINO')
	INSERT INTO TABLA_GENERAL_DETALLE VALUES(8608,53,0,GETDATE(),0,'luis.galan@corpbanca.cl','DESTINO')
	
END