//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace AdminOpciones.SrvValorizador {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvValorizador.SrvValorizadorCarteraSoap")]
    public interface SrvValorizadorCarteraSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetSetPreciosConSpot", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetSetPreciosConSpot(System.DateTime fechaProceso, double Spot, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, System.AsyncCallback callback, object asyncState);
        
        string EndGetSetPreciosConSpot(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetSetPrecios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetSetPrecios(System.DateTime fechaProceso, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, System.AsyncCallback callback, object asyncState);
        
        string EndGetSetPrecios(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getDetContratoFixing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetDetContratoFixing(System.DateTime fechaContrato, string Estado, System.DateTime fechaDeProcesoSistema, System.AsyncCallback callback, object asyncState);
        
        string EndgetDetContratoFixing(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ValorizarCartera", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginValorizarCartera(string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, int setPricing, System.AsyncCallback callback, object asyncState);
        
        string EndValorizarCartera(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Sensibilidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginSensibilidad(string DetContratoAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, int setPricing, System.AsyncCallback callback, object asyncState);
        
        string EndSensibilidad(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/TopologiaVega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginTopologiaVega(string BsSpotBsFwd, string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, string rrfly_callput, int setPricing, System.AsyncCallback callback, object asyncState);
        
        string EndTopologiaVega(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InterpVol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginInterpVol(System.DateTime FechaVal, int plazo, string paridad, double Spot, double Strike, string CurvaDom, string CurvaFor, int SetPrecios, System.AsyncCallback callback, object asyncState);
        
        double EndInterpVol(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CalcularLCR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginCalcularLCR(int _NumeroContrato, string _Operacion, System.AsyncCallback callback, object asyncState);
        
        string EndCalcularLCR(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SrvValorizadorCarteraSoapChannel : AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSetPreciosConSpotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSetPreciosConSpotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSetPreciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSetPreciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDetContratoFixingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDetContratoFixingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValorizarCarteraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValorizarCarteraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SensibilidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SensibilidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TopologiaVegaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TopologiaVegaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterpVolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InterpVolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcularLCRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CalcularLCRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvValorizadorCarteraSoapClient : System.ServiceModel.ClientBase<AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap>, AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap {
        
        private BeginOperationDelegate onBeginGetSetPreciosConSpotDelegate;
        
        private EndOperationDelegate onEndGetSetPreciosConSpotDelegate;
        
        private System.Threading.SendOrPostCallback onGetSetPreciosConSpotCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSetPreciosDelegate;
        
        private EndOperationDelegate onEndGetSetPreciosDelegate;
        
        private System.Threading.SendOrPostCallback onGetSetPreciosCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDetContratoFixingDelegate;
        
        private EndOperationDelegate onEndgetDetContratoFixingDelegate;
        
        private System.Threading.SendOrPostCallback ongetDetContratoFixingCompletedDelegate;
        
        private BeginOperationDelegate onBeginValorizarCarteraDelegate;
        
        private EndOperationDelegate onEndValorizarCarteraDelegate;
        
        private System.Threading.SendOrPostCallback onValorizarCarteraCompletedDelegate;
        
        private BeginOperationDelegate onBeginSensibilidadDelegate;
        
        private EndOperationDelegate onEndSensibilidadDelegate;
        
        private System.Threading.SendOrPostCallback onSensibilidadCompletedDelegate;
        
        private BeginOperationDelegate onBeginTopologiaVegaDelegate;
        
        private EndOperationDelegate onEndTopologiaVegaDelegate;
        
        private System.Threading.SendOrPostCallback onTopologiaVegaCompletedDelegate;
        
        private BeginOperationDelegate onBeginInterpVolDelegate;
        
        private EndOperationDelegate onEndInterpVolDelegate;
        
        private System.Threading.SendOrPostCallback onInterpVolCompletedDelegate;
        
        private BeginOperationDelegate onBeginCalcularLCRDelegate;
        
        private EndOperationDelegate onEndCalcularLCRDelegate;
        
        private System.Threading.SendOrPostCallback onCalcularLCRCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SrvValorizadorCarteraSoapClient() {
        }
        
        public SrvValorizadorCarteraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvValorizadorCarteraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvValorizadorCarteraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvValorizadorCarteraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetSetPreciosConSpotCompletedEventArgs> GetSetPreciosConSpotCompleted;
        
        public event System.EventHandler<GetSetPreciosCompletedEventArgs> GetSetPreciosCompleted;
        
        public event System.EventHandler<getDetContratoFixingCompletedEventArgs> getDetContratoFixingCompleted;
        
        public event System.EventHandler<ValorizarCarteraCompletedEventArgs> ValorizarCarteraCompleted;
        
        public event System.EventHandler<SensibilidadCompletedEventArgs> SensibilidadCompleted;
        
        public event System.EventHandler<TopologiaVegaCompletedEventArgs> TopologiaVegaCompleted;
        
        public event System.EventHandler<InterpVolCompletedEventArgs> InterpVolCompleted;
        
        public event System.EventHandler<CalcularLCRCompletedEventArgs> CalcularLCRCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BeginGetSetPreciosConSpot(System.DateTime fechaProceso, double Spot, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSetPreciosConSpot(fechaProceso, Spot, parMon, nemoMonSpot, idCurvasMonedasXML, enuSetPricing, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndGetSetPreciosConSpot(System.IAsyncResult result) {
            return base.Channel.EndGetSetPreciosConSpot(result);
        }
        
        private System.IAsyncResult OnBeginGetSetPreciosConSpot(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime fechaProceso = ((System.DateTime)(inValues[0]));
            double Spot = ((double)(inValues[1]));
            string parMon = ((string)(inValues[2]));
            string nemoMonSpot = ((string)(inValues[3]));
            string idCurvasMonedasXML = ((string)(inValues[4]));
            int enuSetPricing = ((int)(inValues[5]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BeginGetSetPreciosConSpot(fechaProceso, Spot, parMon, nemoMonSpot, idCurvasMonedasXML, enuSetPricing, callback, asyncState);
        }
        
        private object[] OnEndGetSetPreciosConSpot(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndGetSetPreciosConSpot(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSetPreciosConSpotCompleted(object state) {
            if ((this.GetSetPreciosConSpotCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSetPreciosConSpotCompleted(this, new GetSetPreciosConSpotCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSetPreciosConSpotAsync(System.DateTime fechaProceso, double Spot, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing) {
            this.GetSetPreciosConSpotAsync(fechaProceso, Spot, parMon, nemoMonSpot, idCurvasMonedasXML, enuSetPricing, null);
        }
        
        public void GetSetPreciosConSpotAsync(System.DateTime fechaProceso, double Spot, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, object userState) {
            if ((this.onBeginGetSetPreciosConSpotDelegate == null)) {
                this.onBeginGetSetPreciosConSpotDelegate = new BeginOperationDelegate(this.OnBeginGetSetPreciosConSpot);
            }
            if ((this.onEndGetSetPreciosConSpotDelegate == null)) {
                this.onEndGetSetPreciosConSpotDelegate = new EndOperationDelegate(this.OnEndGetSetPreciosConSpot);
            }
            if ((this.onGetSetPreciosConSpotCompletedDelegate == null)) {
                this.onGetSetPreciosConSpotCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSetPreciosConSpotCompleted);
            }
            base.InvokeAsync(this.onBeginGetSetPreciosConSpotDelegate, new object[] {
                        fechaProceso,
                        Spot,
                        parMon,
                        nemoMonSpot,
                        idCurvasMonedasXML,
                        enuSetPricing}, this.onEndGetSetPreciosConSpotDelegate, this.onGetSetPreciosConSpotCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BeginGetSetPrecios(System.DateTime fechaProceso, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSetPrecios(fechaProceso, parMon, nemoMonSpot, idCurvasMonedasXML, enuSetPricing, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndGetSetPrecios(System.IAsyncResult result) {
            return base.Channel.EndGetSetPrecios(result);
        }
        
        private System.IAsyncResult OnBeginGetSetPrecios(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime fechaProceso = ((System.DateTime)(inValues[0]));
            string parMon = ((string)(inValues[1]));
            string nemoMonSpot = ((string)(inValues[2]));
            string idCurvasMonedasXML = ((string)(inValues[3]));
            int enuSetPricing = ((int)(inValues[4]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BeginGetSetPrecios(fechaProceso, parMon, nemoMonSpot, idCurvasMonedasXML, enuSetPricing, callback, asyncState);
        }
        
        private object[] OnEndGetSetPrecios(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndGetSetPrecios(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSetPreciosCompleted(object state) {
            if ((this.GetSetPreciosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSetPreciosCompleted(this, new GetSetPreciosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSetPreciosAsync(System.DateTime fechaProceso, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing) {
            this.GetSetPreciosAsync(fechaProceso, parMon, nemoMonSpot, idCurvasMonedasXML, enuSetPricing, null);
        }
        
        public void GetSetPreciosAsync(System.DateTime fechaProceso, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, object userState) {
            if ((this.onBeginGetSetPreciosDelegate == null)) {
                this.onBeginGetSetPreciosDelegate = new BeginOperationDelegate(this.OnBeginGetSetPrecios);
            }
            if ((this.onEndGetSetPreciosDelegate == null)) {
                this.onEndGetSetPreciosDelegate = new EndOperationDelegate(this.OnEndGetSetPrecios);
            }
            if ((this.onGetSetPreciosCompletedDelegate == null)) {
                this.onGetSetPreciosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSetPreciosCompleted);
            }
            base.InvokeAsync(this.onBeginGetSetPreciosDelegate, new object[] {
                        fechaProceso,
                        parMon,
                        nemoMonSpot,
                        idCurvasMonedasXML,
                        enuSetPricing}, this.onEndGetSetPreciosDelegate, this.onGetSetPreciosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BegingetDetContratoFixing(System.DateTime fechaContrato, string Estado, System.DateTime fechaDeProcesoSistema, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDetContratoFixing(fechaContrato, Estado, fechaDeProcesoSistema, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndgetDetContratoFixing(System.IAsyncResult result) {
            return base.Channel.EndgetDetContratoFixing(result);
        }
        
        private System.IAsyncResult OnBegingetDetContratoFixing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime fechaContrato = ((System.DateTime)(inValues[0]));
            string Estado = ((string)(inValues[1]));
            System.DateTime fechaDeProcesoSistema = ((System.DateTime)(inValues[2]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BegingetDetContratoFixing(fechaContrato, Estado, fechaDeProcesoSistema, callback, asyncState);
        }
        
        private object[] OnEndgetDetContratoFixing(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndgetDetContratoFixing(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDetContratoFixingCompleted(object state) {
            if ((this.getDetContratoFixingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDetContratoFixingCompleted(this, new getDetContratoFixingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDetContratoFixingAsync(System.DateTime fechaContrato, string Estado, System.DateTime fechaDeProcesoSistema) {
            this.getDetContratoFixingAsync(fechaContrato, Estado, fechaDeProcesoSistema, null);
        }
        
        public void getDetContratoFixingAsync(System.DateTime fechaContrato, string Estado, System.DateTime fechaDeProcesoSistema, object userState) {
            if ((this.onBegingetDetContratoFixingDelegate == null)) {
                this.onBegingetDetContratoFixingDelegate = new BeginOperationDelegate(this.OnBegingetDetContratoFixing);
            }
            if ((this.onEndgetDetContratoFixingDelegate == null)) {
                this.onEndgetDetContratoFixingDelegate = new EndOperationDelegate(this.OnEndgetDetContratoFixing);
            }
            if ((this.ongetDetContratoFixingCompletedDelegate == null)) {
                this.ongetDetContratoFixingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDetContratoFixingCompleted);
            }
            base.InvokeAsync(this.onBegingetDetContratoFixingDelegate, new object[] {
                        fechaContrato,
                        Estado,
                        fechaDeProcesoSistema}, this.onEndgetDetContratoFixingDelegate, this.ongetDetContratoFixingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BeginValorizarCartera(string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, int setPricing, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValorizarCartera(DetContraToAndFixingData, FechaSetdePrecios, setPricing, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndValorizarCartera(System.IAsyncResult result) {
            return base.Channel.EndValorizarCartera(result);
        }
        
        private System.IAsyncResult OnBeginValorizarCartera(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string DetContraToAndFixingData = ((string)(inValues[0]));
            System.DateTime FechaSetdePrecios = ((System.DateTime)(inValues[1]));
            int setPricing = ((int)(inValues[2]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BeginValorizarCartera(DetContraToAndFixingData, FechaSetdePrecios, setPricing, callback, asyncState);
        }
        
        private object[] OnEndValorizarCartera(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndValorizarCartera(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValorizarCarteraCompleted(object state) {
            if ((this.ValorizarCarteraCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValorizarCarteraCompleted(this, new ValorizarCarteraCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValorizarCarteraAsync(string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, int setPricing) {
            this.ValorizarCarteraAsync(DetContraToAndFixingData, FechaSetdePrecios, setPricing, null);
        }
        
        public void ValorizarCarteraAsync(string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, int setPricing, object userState) {
            if ((this.onBeginValorizarCarteraDelegate == null)) {
                this.onBeginValorizarCarteraDelegate = new BeginOperationDelegate(this.OnBeginValorizarCartera);
            }
            if ((this.onEndValorizarCarteraDelegate == null)) {
                this.onEndValorizarCarteraDelegate = new EndOperationDelegate(this.OnEndValorizarCartera);
            }
            if ((this.onValorizarCarteraCompletedDelegate == null)) {
                this.onValorizarCarteraCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValorizarCarteraCompleted);
            }
            base.InvokeAsync(this.onBeginValorizarCarteraDelegate, new object[] {
                        DetContraToAndFixingData,
                        FechaSetdePrecios,
                        setPricing}, this.onEndValorizarCarteraDelegate, this.onValorizarCarteraCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BeginSensibilidad(string DetContratoAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, int setPricing, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSensibilidad(DetContratoAndFixingData, FechaSetdePrecios, MTM_Totalizador, setPricing, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndSensibilidad(System.IAsyncResult result) {
            return base.Channel.EndSensibilidad(result);
        }
        
        private System.IAsyncResult OnBeginSensibilidad(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string DetContratoAndFixingData = ((string)(inValues[0]));
            System.DateTime FechaSetdePrecios = ((System.DateTime)(inValues[1]));
            double MTM_Totalizador = ((double)(inValues[2]));
            int setPricing = ((int)(inValues[3]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BeginSensibilidad(DetContratoAndFixingData, FechaSetdePrecios, MTM_Totalizador, setPricing, callback, asyncState);
        }
        
        private object[] OnEndSensibilidad(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndSensibilidad(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSensibilidadCompleted(object state) {
            if ((this.SensibilidadCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SensibilidadCompleted(this, new SensibilidadCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SensibilidadAsync(string DetContratoAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, int setPricing) {
            this.SensibilidadAsync(DetContratoAndFixingData, FechaSetdePrecios, MTM_Totalizador, setPricing, null);
        }
        
        public void SensibilidadAsync(string DetContratoAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, int setPricing, object userState) {
            if ((this.onBeginSensibilidadDelegate == null)) {
                this.onBeginSensibilidadDelegate = new BeginOperationDelegate(this.OnBeginSensibilidad);
            }
            if ((this.onEndSensibilidadDelegate == null)) {
                this.onEndSensibilidadDelegate = new EndOperationDelegate(this.OnEndSensibilidad);
            }
            if ((this.onSensibilidadCompletedDelegate == null)) {
                this.onSensibilidadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSensibilidadCompleted);
            }
            base.InvokeAsync(this.onBeginSensibilidadDelegate, new object[] {
                        DetContratoAndFixingData,
                        FechaSetdePrecios,
                        MTM_Totalizador,
                        setPricing}, this.onEndSensibilidadDelegate, this.onSensibilidadCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BeginTopologiaVega(string BsSpotBsFwd, string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, string rrfly_callput, int setPricing, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTopologiaVega(BsSpotBsFwd, DetContraToAndFixingData, FechaSetdePrecios, MTM_Totalizador, rrfly_callput, setPricing, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndTopologiaVega(System.IAsyncResult result) {
            return base.Channel.EndTopologiaVega(result);
        }
        
        private System.IAsyncResult OnBeginTopologiaVega(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string BsSpotBsFwd = ((string)(inValues[0]));
            string DetContraToAndFixingData = ((string)(inValues[1]));
            System.DateTime FechaSetdePrecios = ((System.DateTime)(inValues[2]));
            double MTM_Totalizador = ((double)(inValues[3]));
            string rrfly_callput = ((string)(inValues[4]));
            int setPricing = ((int)(inValues[5]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BeginTopologiaVega(BsSpotBsFwd, DetContraToAndFixingData, FechaSetdePrecios, MTM_Totalizador, rrfly_callput, setPricing, callback, asyncState);
        }
        
        private object[] OnEndTopologiaVega(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndTopologiaVega(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTopologiaVegaCompleted(object state) {
            if ((this.TopologiaVegaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TopologiaVegaCompleted(this, new TopologiaVegaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TopologiaVegaAsync(string BsSpotBsFwd, string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, string rrfly_callput, int setPricing) {
            this.TopologiaVegaAsync(BsSpotBsFwd, DetContraToAndFixingData, FechaSetdePrecios, MTM_Totalizador, rrfly_callput, setPricing, null);
        }
        
        public void TopologiaVegaAsync(string BsSpotBsFwd, string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, string rrfly_callput, int setPricing, object userState) {
            if ((this.onBeginTopologiaVegaDelegate == null)) {
                this.onBeginTopologiaVegaDelegate = new BeginOperationDelegate(this.OnBeginTopologiaVega);
            }
            if ((this.onEndTopologiaVegaDelegate == null)) {
                this.onEndTopologiaVegaDelegate = new EndOperationDelegate(this.OnEndTopologiaVega);
            }
            if ((this.onTopologiaVegaCompletedDelegate == null)) {
                this.onTopologiaVegaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTopologiaVegaCompleted);
            }
            base.InvokeAsync(this.onBeginTopologiaVegaDelegate, new object[] {
                        BsSpotBsFwd,
                        DetContraToAndFixingData,
                        FechaSetdePrecios,
                        MTM_Totalizador,
                        rrfly_callput,
                        setPricing}, this.onEndTopologiaVegaDelegate, this.onTopologiaVegaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BeginInterpVol(System.DateTime FechaVal, int plazo, string paridad, double Spot, double Strike, string CurvaDom, string CurvaFor, int SetPrecios, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInterpVol(FechaVal, plazo, paridad, Spot, Strike, CurvaDom, CurvaFor, SetPrecios, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        double AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndInterpVol(System.IAsyncResult result) {
            return base.Channel.EndInterpVol(result);
        }
        
        private System.IAsyncResult OnBeginInterpVol(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime FechaVal = ((System.DateTime)(inValues[0]));
            int plazo = ((int)(inValues[1]));
            string paridad = ((string)(inValues[2]));
            double Spot = ((double)(inValues[3]));
            double Strike = ((double)(inValues[4]));
            string CurvaDom = ((string)(inValues[5]));
            string CurvaFor = ((string)(inValues[6]));
            int SetPrecios = ((int)(inValues[7]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BeginInterpVol(FechaVal, plazo, paridad, Spot, Strike, CurvaDom, CurvaFor, SetPrecios, callback, asyncState);
        }
        
        private object[] OnEndInterpVol(System.IAsyncResult result) {
            double retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndInterpVol(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInterpVolCompleted(object state) {
            if ((this.InterpVolCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InterpVolCompleted(this, new InterpVolCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InterpVolAsync(System.DateTime FechaVal, int plazo, string paridad, double Spot, double Strike, string CurvaDom, string CurvaFor, int SetPrecios) {
            this.InterpVolAsync(FechaVal, plazo, paridad, Spot, Strike, CurvaDom, CurvaFor, SetPrecios, null);
        }
        
        public void InterpVolAsync(System.DateTime FechaVal, int plazo, string paridad, double Spot, double Strike, string CurvaDom, string CurvaFor, int SetPrecios, object userState) {
            if ((this.onBeginInterpVolDelegate == null)) {
                this.onBeginInterpVolDelegate = new BeginOperationDelegate(this.OnBeginInterpVol);
            }
            if ((this.onEndInterpVolDelegate == null)) {
                this.onEndInterpVolDelegate = new EndOperationDelegate(this.OnEndInterpVol);
            }
            if ((this.onInterpVolCompletedDelegate == null)) {
                this.onInterpVolCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInterpVolCompleted);
            }
            base.InvokeAsync(this.onBeginInterpVolDelegate, new object[] {
                        FechaVal,
                        plazo,
                        paridad,
                        Spot,
                        Strike,
                        CurvaDom,
                        CurvaFor,
                        SetPrecios}, this.onEndInterpVolDelegate, this.onInterpVolCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.BeginCalcularLCR(int _NumeroContrato, string _Operacion, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCalcularLCR(_NumeroContrato, _Operacion, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap.EndCalcularLCR(System.IAsyncResult result) {
            return base.Channel.EndCalcularLCR(result);
        }
        
        private System.IAsyncResult OnBeginCalcularLCR(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _NumeroContrato = ((int)(inValues[0]));
            string _Operacion = ((string)(inValues[1]));
            return ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).BeginCalcularLCR(_NumeroContrato, _Operacion, callback, asyncState);
        }
        
        private object[] OnEndCalcularLCR(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap)(this)).EndCalcularLCR(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCalcularLCRCompleted(object state) {
            if ((this.CalcularLCRCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CalcularLCRCompleted(this, new CalcularLCRCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CalcularLCRAsync(int _NumeroContrato, string _Operacion) {
            this.CalcularLCRAsync(_NumeroContrato, _Operacion, null);
        }
        
        public void CalcularLCRAsync(int _NumeroContrato, string _Operacion, object userState) {
            if ((this.onBeginCalcularLCRDelegate == null)) {
                this.onBeginCalcularLCRDelegate = new BeginOperationDelegate(this.OnBeginCalcularLCR);
            }
            if ((this.onEndCalcularLCRDelegate == null)) {
                this.onEndCalcularLCRDelegate = new EndOperationDelegate(this.OnEndCalcularLCR);
            }
            if ((this.onCalcularLCRCompletedDelegate == null)) {
                this.onCalcularLCRCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCalcularLCRCompleted);
            }
            base.InvokeAsync(this.onBeginCalcularLCRDelegate, new object[] {
                        _NumeroContrato,
                        _Operacion}, this.onEndCalcularLCRDelegate, this.onCalcularLCRCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap CreateChannel() {
            return new SrvValorizadorCarteraSoapClientChannel(this);
        }
        
        private class SrvValorizadorCarteraSoapClientChannel : ChannelBase<AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap>, AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap {
            
            public SrvValorizadorCarteraSoapClientChannel(System.ServiceModel.ClientBase<AdminOpciones.SrvValorizador.SrvValorizadorCarteraSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSetPreciosConSpot(System.DateTime fechaProceso, double Spot, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = fechaProceso;
                _args[1] = Spot;
                _args[2] = parMon;
                _args[3] = nemoMonSpot;
                _args[4] = idCurvasMonedasXML;
                _args[5] = enuSetPricing;
                System.IAsyncResult _result = base.BeginInvoke("GetSetPreciosConSpot", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetSetPreciosConSpot(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetSetPreciosConSpot", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSetPrecios(System.DateTime fechaProceso, string parMon, string nemoMonSpot, string idCurvasMonedasXML, int enuSetPricing, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = fechaProceso;
                _args[1] = parMon;
                _args[2] = nemoMonSpot;
                _args[3] = idCurvasMonedasXML;
                _args[4] = enuSetPricing;
                System.IAsyncResult _result = base.BeginInvoke("GetSetPrecios", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetSetPrecios(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetSetPrecios", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDetContratoFixing(System.DateTime fechaContrato, string Estado, System.DateTime fechaDeProcesoSistema, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = fechaContrato;
                _args[1] = Estado;
                _args[2] = fechaDeProcesoSistema;
                System.IAsyncResult _result = base.BeginInvoke("getDetContratoFixing", _args, callback, asyncState);
                return _result;
            }
            
            public string EndgetDetContratoFixing(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("getDetContratoFixing", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginValorizarCartera(string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, int setPricing, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = DetContraToAndFixingData;
                _args[1] = FechaSetdePrecios;
                _args[2] = setPricing;
                System.IAsyncResult _result = base.BeginInvoke("ValorizarCartera", _args, callback, asyncState);
                return _result;
            }
            
            public string EndValorizarCartera(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ValorizarCartera", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSensibilidad(string DetContratoAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, int setPricing, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = DetContratoAndFixingData;
                _args[1] = FechaSetdePrecios;
                _args[2] = MTM_Totalizador;
                _args[3] = setPricing;
                System.IAsyncResult _result = base.BeginInvoke("Sensibilidad", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSensibilidad(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Sensibilidad", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTopologiaVega(string BsSpotBsFwd, string DetContraToAndFixingData, System.DateTime FechaSetdePrecios, double MTM_Totalizador, string rrfly_callput, int setPricing, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = BsSpotBsFwd;
                _args[1] = DetContraToAndFixingData;
                _args[2] = FechaSetdePrecios;
                _args[3] = MTM_Totalizador;
                _args[4] = rrfly_callput;
                _args[5] = setPricing;
                System.IAsyncResult _result = base.BeginInvoke("TopologiaVega", _args, callback, asyncState);
                return _result;
            }
            
            public string EndTopologiaVega(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("TopologiaVega", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInterpVol(System.DateTime FechaVal, int plazo, string paridad, double Spot, double Strike, string CurvaDom, string CurvaFor, int SetPrecios, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = FechaVal;
                _args[1] = plazo;
                _args[2] = paridad;
                _args[3] = Spot;
                _args[4] = Strike;
                _args[5] = CurvaDom;
                _args[6] = CurvaFor;
                _args[7] = SetPrecios;
                System.IAsyncResult _result = base.BeginInvoke("InterpVol", _args, callback, asyncState);
                return _result;
            }
            
            public double EndInterpVol(System.IAsyncResult result) {
                object[] _args = new object[0];
                double _result = ((double)(base.EndInvoke("InterpVol", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCalcularLCR(int _NumeroContrato, string _Operacion, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _NumeroContrato;
                _args[1] = _Operacion;
                System.IAsyncResult _result = base.BeginInvoke("CalcularLCR", _args, callback, asyncState);
                return _result;
            }
            
            public string EndCalcularLCR(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("CalcularLCR", _args, result)));
                return _result;
            }
        }
    }
}
