//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCM_ODS_Testing.wsRCM_ODS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://fmdsfmc.corpbanca.cl/fmd", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd", ConfigurationName="wsRCM_ODS.wsReportServicesSoap")]
    public interface wsReportServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reportType del espacio de nombres http://fmdsfmc.corpbanca.cl/fmd no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://fmdsfmc.corpbanca.cl/fmd/GenerateAndSendReports", ReplyAction="*")]
        RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsResponse GenerateAndSendReports(RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reportType del espacio de nombres http://fmdsfmc.corpbanca.cl/fmd no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://fmdsfmc.corpbanca.cl/fmd/Automated_RCM_SendReports", ReplyAction="*")]
        RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsResponse Automated_RCM_SendReports(RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAndSendReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAndSendReports", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsRequestBody Body;
        
        public GenerateAndSendReportsRequest() {
        }
        
        public GenerateAndSendReportsRequest(RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class GenerateAndSendReportsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WindowsServiceFMD.WebServiceFMD.ProcessType process;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reportType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool withMergeFiles;
        
        public GenerateAndSendReportsRequestBody() {
        }
        
        public GenerateAndSendReportsRequestBody(WindowsServiceFMD.WebServiceFMD.ProcessType process, string reportType, string modulo, string date, bool withMergeFiles) {
            this.process = process;
            this.reportType = reportType;
            this.modulo = modulo;
            this.date = date;
            this.withMergeFiles = withMergeFiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAndSendReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAndSendReportsResponse", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsResponseBody Body;
        
        public GenerateAndSendReportsResponse() {
        }
        
        public GenerateAndSendReportsResponse(RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class GenerateAndSendReportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GenerateAndSendReportsResult;
        
        public GenerateAndSendReportsResponseBody() {
        }
        
        public GenerateAndSendReportsResponseBody(object GenerateAndSendReportsResult) {
            this.GenerateAndSendReportsResult = GenerateAndSendReportsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Automated_RCM_SendReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Automated_RCM_SendReports", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsRequestBody Body;
        
        public Automated_RCM_SendReportsRequest() {
        }
        
        public Automated_RCM_SendReportsRequest(RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class Automated_RCM_SendReportsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WindowsServiceFMD.WebServiceFMD.ProcessType process;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reportType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        public Automated_RCM_SendReportsRequestBody() {
        }
        
        public Automated_RCM_SendReportsRequestBody(WindowsServiceFMD.WebServiceFMD.ProcessType process, string reportType, string date) {
            this.process = process;
            this.reportType = reportType;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Automated_RCM_SendReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Automated_RCM_SendReportsResponse", Namespace="http://fmdsfmc.corpbanca.cl/fmd", Order=0)]
        public RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsResponseBody Body;
        
        public Automated_RCM_SendReportsResponse() {
        }
        
        public Automated_RCM_SendReportsResponse(RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fmdsfmc.corpbanca.cl/fmd")]
    public partial class Automated_RCM_SendReportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCM_ODS_Testing.wsRCM_ODS.ArrayOfString Automated_RCM_SendReportsResult;
        
        public Automated_RCM_SendReportsResponseBody() {
        }
        
        public Automated_RCM_SendReportsResponseBody(RCM_ODS_Testing.wsRCM_ODS.ArrayOfString Automated_RCM_SendReportsResult) {
            this.Automated_RCM_SendReportsResult = Automated_RCM_SendReportsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsReportServicesSoapChannel : RCM_ODS_Testing.wsRCM_ODS.wsReportServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsReportServicesSoapClient : System.ServiceModel.ClientBase<RCM_ODS_Testing.wsRCM_ODS.wsReportServicesSoap>, RCM_ODS_Testing.wsRCM_ODS.wsReportServicesSoap {
        
        public wsReportServicesSoapClient() {
        }
        
        public wsReportServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsReportServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReportServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReportServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsResponse RCM_ODS_Testing.wsRCM_ODS.wsReportServicesSoap.GenerateAndSendReports(RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsRequest request) {
            return base.Channel.GenerateAndSendReports(request);
        }
        
        public object GenerateAndSendReports(WindowsServiceFMD.WebServiceFMD.ProcessType process, string reportType, string modulo, string date, bool withMergeFiles) {
            RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsRequest inValue = new RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsRequest();
            inValue.Body = new RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsRequestBody();
            inValue.Body.process = process;
            inValue.Body.reportType = reportType;
            inValue.Body.modulo = modulo;
            inValue.Body.date = date;
            inValue.Body.withMergeFiles = withMergeFiles;
            RCM_ODS_Testing.wsRCM_ODS.GenerateAndSendReportsResponse retVal = ((RCM_ODS_Testing.wsRCM_ODS.wsReportServicesSoap)(this)).GenerateAndSendReports(inValue);
            return retVal.Body.GenerateAndSendReportsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsResponse RCM_ODS_Testing.wsRCM_ODS.wsReportServicesSoap.Automated_RCM_SendReports(RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsRequest request) {
            return base.Channel.Automated_RCM_SendReports(request);
        }
        
        public RCM_ODS_Testing.wsRCM_ODS.ArrayOfString Automated_RCM_SendReports(WindowsServiceFMD.WebServiceFMD.ProcessType process, string reportType, string date) {
            RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsRequest inValue = new RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsRequest();
            inValue.Body = new RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsRequestBody();
            inValue.Body.process = process;
            inValue.Body.reportType = reportType;
            inValue.Body.date = date;
            RCM_ODS_Testing.wsRCM_ODS.Automated_RCM_SendReportsResponse retVal = ((RCM_ODS_Testing.wsRCM_ODS.wsReportServicesSoap)(this)).Automated_RCM_SendReports(inValue);
            return retVal.Body.Automated_RCM_SendReportsResult;
        }
    }
}
