//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace AdminOpciones.SrvLeasing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvLeasing.LeasingSoap")]
    public interface LeasingSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ValidaLeasingACLSC1001", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginValidaLeasingACLSC1001(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, System.AsyncCallback callback, object asyncState);
        
        string EndValidaLeasingACLSC1001(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ConsultaLeasingACLSC1002", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginConsultaLeasingACLSC1002(System.AsyncCallback callback, object asyncState);
        
        string EndConsultaLeasingACLSC1002(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LeasingSoapChannel : AdminOpciones.SrvLeasing.LeasingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidaLeasingACLSC1001CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidaLeasingACLSC1001CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConsultaLeasingACLSC1002CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaLeasingACLSC1002CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LeasingSoapClient : System.ServiceModel.ClientBase<AdminOpciones.SrvLeasing.LeasingSoap>, AdminOpciones.SrvLeasing.LeasingSoap {
        
        private BeginOperationDelegate onBeginValidaLeasingACLSC1001Delegate;
        
        private EndOperationDelegate onEndValidaLeasingACLSC1001Delegate;
        
        private System.Threading.SendOrPostCallback onValidaLeasingACLSC1001CompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaLeasingACLSC1002Delegate;
        
        private EndOperationDelegate onEndConsultaLeasingACLSC1002Delegate;
        
        private System.Threading.SendOrPostCallback onConsultaLeasingACLSC1002CompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LeasingSoapClient() {
        }
        
        public LeasingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeasingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeasingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeasingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ValidaLeasingACLSC1001CompletedEventArgs> ValidaLeasingACLSC1001Completed;
        
        public event System.EventHandler<ConsultaLeasingACLSC1002CompletedEventArgs> ConsultaLeasingACLSC1002Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvLeasing.LeasingSoap.BeginValidaLeasingACLSC1001(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidaLeasingACLSC1001(RutCliente, NumeroLeasing, NumeroGrupoBien, MontoBien, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvLeasing.LeasingSoap.EndValidaLeasingACLSC1001(System.IAsyncResult result) {
            return base.Channel.EndValidaLeasingACLSC1001(result);
        }
        
        private System.IAsyncResult OnBeginValidaLeasingACLSC1001(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string RutCliente = ((string)(inValues[0]));
            string NumeroLeasing = ((string)(inValues[1]));
            string NumeroGrupoBien = ((string)(inValues[2]));
            string MontoBien = ((string)(inValues[3]));
            return ((AdminOpciones.SrvLeasing.LeasingSoap)(this)).BeginValidaLeasingACLSC1001(RutCliente, NumeroLeasing, NumeroGrupoBien, MontoBien, callback, asyncState);
        }
        
        private object[] OnEndValidaLeasingACLSC1001(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvLeasing.LeasingSoap)(this)).EndValidaLeasingACLSC1001(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidaLeasingACLSC1001Completed(object state) {
            if ((this.ValidaLeasingACLSC1001Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidaLeasingACLSC1001Completed(this, new ValidaLeasingACLSC1001CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidaLeasingACLSC1001Async(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien) {
            this.ValidaLeasingACLSC1001Async(RutCliente, NumeroLeasing, NumeroGrupoBien, MontoBien, null);
        }
        
        public void ValidaLeasingACLSC1001Async(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, object userState) {
            if ((this.onBeginValidaLeasingACLSC1001Delegate == null)) {
                this.onBeginValidaLeasingACLSC1001Delegate = new BeginOperationDelegate(this.OnBeginValidaLeasingACLSC1001);
            }
            if ((this.onEndValidaLeasingACLSC1001Delegate == null)) {
                this.onEndValidaLeasingACLSC1001Delegate = new EndOperationDelegate(this.OnEndValidaLeasingACLSC1001);
            }
            if ((this.onValidaLeasingACLSC1001CompletedDelegate == null)) {
                this.onValidaLeasingACLSC1001CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidaLeasingACLSC1001Completed);
            }
            base.InvokeAsync(this.onBeginValidaLeasingACLSC1001Delegate, new object[] {
                        RutCliente,
                        NumeroLeasing,
                        NumeroGrupoBien,
                        MontoBien}, this.onEndValidaLeasingACLSC1001Delegate, this.onValidaLeasingACLSC1001CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvLeasing.LeasingSoap.BeginConsultaLeasingACLSC1002(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaLeasingACLSC1002(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string AdminOpciones.SrvLeasing.LeasingSoap.EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            return base.Channel.EndConsultaLeasingACLSC1002(result);
        }
        
        private System.IAsyncResult OnBeginConsultaLeasingACLSC1002(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AdminOpciones.SrvLeasing.LeasingSoap)(this)).BeginConsultaLeasingACLSC1002(callback, asyncState);
        }
        
        private object[] OnEndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            string retVal = ((AdminOpciones.SrvLeasing.LeasingSoap)(this)).EndConsultaLeasingACLSC1002(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaLeasingACLSC1002Completed(object state) {
            if ((this.ConsultaLeasingACLSC1002Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaLeasingACLSC1002Completed(this, new ConsultaLeasingACLSC1002CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaLeasingACLSC1002Async() {
            this.ConsultaLeasingACLSC1002Async(null);
        }
        
        public void ConsultaLeasingACLSC1002Async(object userState) {
            if ((this.onBeginConsultaLeasingACLSC1002Delegate == null)) {
                this.onBeginConsultaLeasingACLSC1002Delegate = new BeginOperationDelegate(this.OnBeginConsultaLeasingACLSC1002);
            }
            if ((this.onEndConsultaLeasingACLSC1002Delegate == null)) {
                this.onEndConsultaLeasingACLSC1002Delegate = new EndOperationDelegate(this.OnEndConsultaLeasingACLSC1002);
            }
            if ((this.onConsultaLeasingACLSC1002CompletedDelegate == null)) {
                this.onConsultaLeasingACLSC1002CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaLeasingACLSC1002Completed);
            }
            base.InvokeAsync(this.onBeginConsultaLeasingACLSC1002Delegate, null, this.onEndConsultaLeasingACLSC1002Delegate, this.onConsultaLeasingACLSC1002CompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AdminOpciones.SrvLeasing.LeasingSoap CreateChannel() {
            return new LeasingSoapClientChannel(this);
        }
        
        private class LeasingSoapClientChannel : ChannelBase<AdminOpciones.SrvLeasing.LeasingSoap>, AdminOpciones.SrvLeasing.LeasingSoap {
            
            public LeasingSoapClientChannel(System.ServiceModel.ClientBase<AdminOpciones.SrvLeasing.LeasingSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginValidaLeasingACLSC1001(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = RutCliente;
                _args[1] = NumeroLeasing;
                _args[2] = NumeroGrupoBien;
                _args[3] = MontoBien;
                System.IAsyncResult _result = base.BeginInvoke("ValidaLeasingACLSC1001", _args, callback, asyncState);
                return _result;
            }
            
            public string EndValidaLeasingACLSC1001(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ValidaLeasingACLSC1001", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultaLeasingACLSC1002(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ConsultaLeasingACLSC1002", _args, callback, asyncState);
                return _result;
            }
            
            public string EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ConsultaLeasingACLSC1002", _args, result)));
                return _result;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvLeasing.LeasingHttpGet")]
    public interface LeasingHttpGet {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LeasingHttpGet/ValidaLeasingACLSC1001Request", ReplyAction="http://tempuri.org/LeasingHttpGet/ValidaLeasingACLSC1001Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginValidaLeasingACLSC1001(AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request request, System.AsyncCallback callback, object asyncState);
        
        AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response EndValidaLeasingACLSC1001(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LeasingHttpGet/ConsultaLeasingACLSC1002Request", ReplyAction="http://tempuri.org/LeasingHttpGet/ConsultaLeasingACLSC1002Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginConsultaLeasingACLSC1002(AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request request, System.AsyncCallback callback, object asyncState);
        
        AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response EndConsultaLeasingACLSC1002(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaLeasingACLSC1001Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RutCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string NumeroLeasing;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string NumeroGrupoBien;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string MontoBien;
        
        public ValidaLeasingACLSC1001Request() {
        }
        
        public ValidaLeasingACLSC1001Request(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien) {
            this.RutCliente = RutCliente;
            this.NumeroLeasing = NumeroLeasing;
            this.NumeroGrupoBien = NumeroGrupoBien;
            this.MontoBien = MontoBien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaLeasingACLSC1001Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public ValidaLeasingACLSC1001Response() {
        }
        
        public ValidaLeasingACLSC1001Response(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLeasingACLSC1002Request {
        
        public ConsultaLeasingACLSC1002Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLeasingACLSC1002Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public ConsultaLeasingACLSC1002Response() {
        }
        
        public ConsultaLeasingACLSC1002Response(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LeasingHttpGetChannel : AdminOpciones.SrvLeasing.LeasingHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidaLeasingACLSC1001CompletedEventArgs1 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidaLeasingACLSC1001CompletedEventArgs1(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConsultaLeasingACLSC1002CompletedEventArgs1 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaLeasingACLSC1002CompletedEventArgs1(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LeasingHttpGetClient : System.ServiceModel.ClientBase<AdminOpciones.SrvLeasing.LeasingHttpGet>, AdminOpciones.SrvLeasing.LeasingHttpGet {
        
        private BeginOperationDelegate onBeginValidaLeasingACLSC1001Delegate;
        
        private EndOperationDelegate onEndValidaLeasingACLSC1001Delegate;
        
        private System.Threading.SendOrPostCallback onValidaLeasingACLSC1001CompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaLeasingACLSC1002Delegate;
        
        private EndOperationDelegate onEndConsultaLeasingACLSC1002Delegate;
        
        private System.Threading.SendOrPostCallback onConsultaLeasingACLSC1002CompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LeasingHttpGetClient() {
        }
        
        public LeasingHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeasingHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeasingHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeasingHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ValidaLeasingACLSC1001CompletedEventArgs1> ValidaLeasingACLSC1001Completed;
        
        public event System.EventHandler<ConsultaLeasingACLSC1002CompletedEventArgs1> ConsultaLeasingACLSC1002Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvLeasing.LeasingHttpGet.BeginValidaLeasingACLSC1001(AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidaLeasingACLSC1001(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginValidaLeasingACLSC1001(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, System.AsyncCallback callback, object asyncState) {
            AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request inValue = new AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request();
            inValue.RutCliente = RutCliente;
            inValue.NumeroLeasing = NumeroLeasing;
            inValue.NumeroGrupoBien = NumeroGrupoBien;
            inValue.MontoBien = MontoBien;
            return ((AdminOpciones.SrvLeasing.LeasingHttpGet)(this)).BeginValidaLeasingACLSC1001(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response AdminOpciones.SrvLeasing.LeasingHttpGet.EndValidaLeasingACLSC1001(System.IAsyncResult result) {
            return base.Channel.EndValidaLeasingACLSC1001(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndValidaLeasingACLSC1001(System.IAsyncResult result) {
            AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response retVal = ((AdminOpciones.SrvLeasing.LeasingHttpGet)(this)).EndValidaLeasingACLSC1001(result);
            return retVal.@string;
        }
        
        private System.IAsyncResult OnBeginValidaLeasingACLSC1001(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string RutCliente = ((string)(inValues[0]));
            string NumeroLeasing = ((string)(inValues[1]));
            string NumeroGrupoBien = ((string)(inValues[2]));
            string MontoBien = ((string)(inValues[3]));
            return this.BeginValidaLeasingACLSC1001(RutCliente, NumeroLeasing, NumeroGrupoBien, MontoBien, callback, asyncState);
        }
        
        private object[] OnEndValidaLeasingACLSC1001(System.IAsyncResult result) {
            string retVal = this.EndValidaLeasingACLSC1001(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidaLeasingACLSC1001Completed(object state) {
            if ((this.ValidaLeasingACLSC1001Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidaLeasingACLSC1001Completed(this, new ValidaLeasingACLSC1001CompletedEventArgs1(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidaLeasingACLSC1001Async(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien) {
            this.ValidaLeasingACLSC1001Async(RutCliente, NumeroLeasing, NumeroGrupoBien, MontoBien, null);
        }
        
        public void ValidaLeasingACLSC1001Async(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, object userState) {
            if ((this.onBeginValidaLeasingACLSC1001Delegate == null)) {
                this.onBeginValidaLeasingACLSC1001Delegate = new BeginOperationDelegate(this.OnBeginValidaLeasingACLSC1001);
            }
            if ((this.onEndValidaLeasingACLSC1001Delegate == null)) {
                this.onEndValidaLeasingACLSC1001Delegate = new EndOperationDelegate(this.OnEndValidaLeasingACLSC1001);
            }
            if ((this.onValidaLeasingACLSC1001CompletedDelegate == null)) {
                this.onValidaLeasingACLSC1001CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidaLeasingACLSC1001Completed);
            }
            base.InvokeAsync(this.onBeginValidaLeasingACLSC1001Delegate, new object[] {
                        RutCliente,
                        NumeroLeasing,
                        NumeroGrupoBien,
                        MontoBien}, this.onEndValidaLeasingACLSC1001Delegate, this.onValidaLeasingACLSC1001CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvLeasing.LeasingHttpGet.BeginConsultaLeasingACLSC1002(AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaLeasingACLSC1002(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginConsultaLeasingACLSC1002(System.AsyncCallback callback, object asyncState) {
            AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request inValue = new AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request();
            return ((AdminOpciones.SrvLeasing.LeasingHttpGet)(this)).BeginConsultaLeasingACLSC1002(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response AdminOpciones.SrvLeasing.LeasingHttpGet.EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            return base.Channel.EndConsultaLeasingACLSC1002(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response retVal = ((AdminOpciones.SrvLeasing.LeasingHttpGet)(this)).EndConsultaLeasingACLSC1002(result);
            return retVal.@string;
        }
        
        private System.IAsyncResult OnBeginConsultaLeasingACLSC1002(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginConsultaLeasingACLSC1002(callback, asyncState);
        }
        
        private object[] OnEndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            string retVal = this.EndConsultaLeasingACLSC1002(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaLeasingACLSC1002Completed(object state) {
            if ((this.ConsultaLeasingACLSC1002Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaLeasingACLSC1002Completed(this, new ConsultaLeasingACLSC1002CompletedEventArgs1(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaLeasingACLSC1002Async() {
            this.ConsultaLeasingACLSC1002Async(null);
        }
        
        public void ConsultaLeasingACLSC1002Async(object userState) {
            if ((this.onBeginConsultaLeasingACLSC1002Delegate == null)) {
                this.onBeginConsultaLeasingACLSC1002Delegate = new BeginOperationDelegate(this.OnBeginConsultaLeasingACLSC1002);
            }
            if ((this.onEndConsultaLeasingACLSC1002Delegate == null)) {
                this.onEndConsultaLeasingACLSC1002Delegate = new EndOperationDelegate(this.OnEndConsultaLeasingACLSC1002);
            }
            if ((this.onConsultaLeasingACLSC1002CompletedDelegate == null)) {
                this.onConsultaLeasingACLSC1002CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaLeasingACLSC1002Completed);
            }
            base.InvokeAsync(this.onBeginConsultaLeasingACLSC1002Delegate, null, this.onEndConsultaLeasingACLSC1002Delegate, this.onConsultaLeasingACLSC1002CompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AdminOpciones.SrvLeasing.LeasingHttpGet CreateChannel() {
            return new LeasingHttpGetClientChannel(this);
        }
        
        private class LeasingHttpGetClientChannel : ChannelBase<AdminOpciones.SrvLeasing.LeasingHttpGet>, AdminOpciones.SrvLeasing.LeasingHttpGet {
            
            public LeasingHttpGetClientChannel(System.ServiceModel.ClientBase<AdminOpciones.SrvLeasing.LeasingHttpGet> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginValidaLeasingACLSC1001(AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ValidaLeasingACLSC1001", _args, callback, asyncState);
                return _result;
            }
            
            public AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response EndValidaLeasingACLSC1001(System.IAsyncResult result) {
                object[] _args = new object[0];
                AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response _result = ((AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response)(base.EndInvoke("ValidaLeasingACLSC1001", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultaLeasingACLSC1002(AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ConsultaLeasingACLSC1002", _args, callback, asyncState);
                return _result;
            }
            
            public AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
                object[] _args = new object[0];
                AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response _result = ((AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response)(base.EndInvoke("ConsultaLeasingACLSC1002", _args, result)));
                return _result;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvLeasing.LeasingHttpPost")]
    public interface LeasingHttpPost {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LeasingHttpPost/ValidaLeasingACLSC1001Request", ReplyAction="http://tempuri.org/LeasingHttpPost/ValidaLeasingACLSC1001Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginValidaLeasingACLSC1001(AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request1 request, System.AsyncCallback callback, object asyncState);
        
        AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response1 EndValidaLeasingACLSC1001(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LeasingHttpPost/ConsultaLeasingACLSC1002Request", ReplyAction="http://tempuri.org/LeasingHttpPost/ConsultaLeasingACLSC1002Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginConsultaLeasingACLSC1002(AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request1 request, System.AsyncCallback callback, object asyncState);
        
        AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response1 EndConsultaLeasingACLSC1002(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaLeasingACLSC1001Request1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RutCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string NumeroLeasing;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string NumeroGrupoBien;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string MontoBien;
        
        public ValidaLeasingACLSC1001Request1() {
        }
        
        public ValidaLeasingACLSC1001Request1(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien) {
            this.RutCliente = RutCliente;
            this.NumeroLeasing = NumeroLeasing;
            this.NumeroGrupoBien = NumeroGrupoBien;
            this.MontoBien = MontoBien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaLeasingACLSC1001Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public ValidaLeasingACLSC1001Response1() {
        }
        
        public ValidaLeasingACLSC1001Response1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLeasingACLSC1002Request1 {
        
        public ConsultaLeasingACLSC1002Request1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLeasingACLSC1002Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public ConsultaLeasingACLSC1002Response1() {
        }
        
        public ConsultaLeasingACLSC1002Response1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LeasingHttpPostChannel : AdminOpciones.SrvLeasing.LeasingHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidaLeasingACLSC1001CompletedEventArgs2 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidaLeasingACLSC1001CompletedEventArgs2(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConsultaLeasingACLSC1002CompletedEventArgs2 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaLeasingACLSC1002CompletedEventArgs2(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LeasingHttpPostClient : System.ServiceModel.ClientBase<AdminOpciones.SrvLeasing.LeasingHttpPost>, AdminOpciones.SrvLeasing.LeasingHttpPost {
        
        private BeginOperationDelegate onBeginValidaLeasingACLSC1001Delegate;
        
        private EndOperationDelegate onEndValidaLeasingACLSC1001Delegate;
        
        private System.Threading.SendOrPostCallback onValidaLeasingACLSC1001CompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaLeasingACLSC1002Delegate;
        
        private EndOperationDelegate onEndConsultaLeasingACLSC1002Delegate;
        
        private System.Threading.SendOrPostCallback onConsultaLeasingACLSC1002CompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LeasingHttpPostClient() {
        }
        
        public LeasingHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeasingHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeasingHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeasingHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ValidaLeasingACLSC1001CompletedEventArgs2> ValidaLeasingACLSC1001Completed;
        
        public event System.EventHandler<ConsultaLeasingACLSC1002CompletedEventArgs2> ConsultaLeasingACLSC1002Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvLeasing.LeasingHttpPost.BeginValidaLeasingACLSC1001(AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidaLeasingACLSC1001(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginValidaLeasingACLSC1001(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, System.AsyncCallback callback, object asyncState) {
            AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request1 inValue = new AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request1();
            inValue.RutCliente = RutCliente;
            inValue.NumeroLeasing = NumeroLeasing;
            inValue.NumeroGrupoBien = NumeroGrupoBien;
            inValue.MontoBien = MontoBien;
            return ((AdminOpciones.SrvLeasing.LeasingHttpPost)(this)).BeginValidaLeasingACLSC1001(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response1 AdminOpciones.SrvLeasing.LeasingHttpPost.EndValidaLeasingACLSC1001(System.IAsyncResult result) {
            return base.Channel.EndValidaLeasingACLSC1001(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndValidaLeasingACLSC1001(System.IAsyncResult result) {
            AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response1 retVal = ((AdminOpciones.SrvLeasing.LeasingHttpPost)(this)).EndValidaLeasingACLSC1001(result);
            return retVal.@string;
        }
        
        private System.IAsyncResult OnBeginValidaLeasingACLSC1001(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string RutCliente = ((string)(inValues[0]));
            string NumeroLeasing = ((string)(inValues[1]));
            string NumeroGrupoBien = ((string)(inValues[2]));
            string MontoBien = ((string)(inValues[3]));
            return this.BeginValidaLeasingACLSC1001(RutCliente, NumeroLeasing, NumeroGrupoBien, MontoBien, callback, asyncState);
        }
        
        private object[] OnEndValidaLeasingACLSC1001(System.IAsyncResult result) {
            string retVal = this.EndValidaLeasingACLSC1001(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidaLeasingACLSC1001Completed(object state) {
            if ((this.ValidaLeasingACLSC1001Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidaLeasingACLSC1001Completed(this, new ValidaLeasingACLSC1001CompletedEventArgs2(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidaLeasingACLSC1001Async(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien) {
            this.ValidaLeasingACLSC1001Async(RutCliente, NumeroLeasing, NumeroGrupoBien, MontoBien, null);
        }
        
        public void ValidaLeasingACLSC1001Async(string RutCliente, string NumeroLeasing, string NumeroGrupoBien, string MontoBien, object userState) {
            if ((this.onBeginValidaLeasingACLSC1001Delegate == null)) {
                this.onBeginValidaLeasingACLSC1001Delegate = new BeginOperationDelegate(this.OnBeginValidaLeasingACLSC1001);
            }
            if ((this.onEndValidaLeasingACLSC1001Delegate == null)) {
                this.onEndValidaLeasingACLSC1001Delegate = new EndOperationDelegate(this.OnEndValidaLeasingACLSC1001);
            }
            if ((this.onValidaLeasingACLSC1001CompletedDelegate == null)) {
                this.onValidaLeasingACLSC1001CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidaLeasingACLSC1001Completed);
            }
            base.InvokeAsync(this.onBeginValidaLeasingACLSC1001Delegate, new object[] {
                        RutCliente,
                        NumeroLeasing,
                        NumeroGrupoBien,
                        MontoBien}, this.onEndValidaLeasingACLSC1001Delegate, this.onValidaLeasingACLSC1001CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AdminOpciones.SrvLeasing.LeasingHttpPost.BeginConsultaLeasingACLSC1002(AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaLeasingACLSC1002(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginConsultaLeasingACLSC1002(System.AsyncCallback callback, object asyncState) {
            AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request1 inValue = new AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request1();
            return ((AdminOpciones.SrvLeasing.LeasingHttpPost)(this)).BeginConsultaLeasingACLSC1002(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response1 AdminOpciones.SrvLeasing.LeasingHttpPost.EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            return base.Channel.EndConsultaLeasingACLSC1002(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response1 retVal = ((AdminOpciones.SrvLeasing.LeasingHttpPost)(this)).EndConsultaLeasingACLSC1002(result);
            return retVal.@string;
        }
        
        private System.IAsyncResult OnBeginConsultaLeasingACLSC1002(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginConsultaLeasingACLSC1002(callback, asyncState);
        }
        
        private object[] OnEndConsultaLeasingACLSC1002(System.IAsyncResult result) {
            string retVal = this.EndConsultaLeasingACLSC1002(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaLeasingACLSC1002Completed(object state) {
            if ((this.ConsultaLeasingACLSC1002Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaLeasingACLSC1002Completed(this, new ConsultaLeasingACLSC1002CompletedEventArgs2(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaLeasingACLSC1002Async() {
            this.ConsultaLeasingACLSC1002Async(null);
        }
        
        public void ConsultaLeasingACLSC1002Async(object userState) {
            if ((this.onBeginConsultaLeasingACLSC1002Delegate == null)) {
                this.onBeginConsultaLeasingACLSC1002Delegate = new BeginOperationDelegate(this.OnBeginConsultaLeasingACLSC1002);
            }
            if ((this.onEndConsultaLeasingACLSC1002Delegate == null)) {
                this.onEndConsultaLeasingACLSC1002Delegate = new EndOperationDelegate(this.OnEndConsultaLeasingACLSC1002);
            }
            if ((this.onConsultaLeasingACLSC1002CompletedDelegate == null)) {
                this.onConsultaLeasingACLSC1002CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaLeasingACLSC1002Completed);
            }
            base.InvokeAsync(this.onBeginConsultaLeasingACLSC1002Delegate, null, this.onEndConsultaLeasingACLSC1002Delegate, this.onConsultaLeasingACLSC1002CompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AdminOpciones.SrvLeasing.LeasingHttpPost CreateChannel() {
            return new LeasingHttpPostClientChannel(this);
        }
        
        private class LeasingHttpPostClientChannel : ChannelBase<AdminOpciones.SrvLeasing.LeasingHttpPost>, AdminOpciones.SrvLeasing.LeasingHttpPost {
            
            public LeasingHttpPostClientChannel(System.ServiceModel.ClientBase<AdminOpciones.SrvLeasing.LeasingHttpPost> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginValidaLeasingACLSC1001(AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Request1 request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ValidaLeasingACLSC1001", _args, callback, asyncState);
                return _result;
            }
            
            public AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response1 EndValidaLeasingACLSC1001(System.IAsyncResult result) {
                object[] _args = new object[0];
                AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response1 _result = ((AdminOpciones.SrvLeasing.ValidaLeasingACLSC1001Response1)(base.EndInvoke("ValidaLeasingACLSC1001", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultaLeasingACLSC1002(AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Request1 request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ConsultaLeasingACLSC1002", _args, callback, asyncState);
                return _result;
            }
            
            public AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response1 EndConsultaLeasingACLSC1002(System.IAsyncResult result) {
                object[] _args = new object[0];
                AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response1 _result = ((AdminOpciones.SrvLeasing.ConsultaLeasingACLSC1002Response1)(base.EndInvoke("ConsultaLeasingACLSC1002", _args, result)));
                return _result;
            }
        }
    }
}
